### PR TITLE
[WIP] Integration of VF# for VS2017 15.9 tag

### PR DESCRIPTION
**Pull request by baronfel**
This is the integration of the 15.9 release tag from the VisualFSharp repo, which should correspond to version number 10.3.x according to the [versioning plan](https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1004-versioning-plan.md). This merge came from the tag [Visual-Studio-2017-Version-15.9](https://github.com/Microsoft/visualfsharp/releases/tag/Visual-Studio-2017-Version-15.9).  This should bring this repo into sync with that release and make the next merges less complex.

~~I'm currently getting a build error on FSharp.Core itself relating to byref~~ Edit: This was a local environmental error, Travis doesn't reproduce.

### CODE REVIEW

**Comment by baronfel** [comment]
Related to this a bit is some confusion I had around which version numbers were to be reported where. Currently FSC reports 10.2.3 when invoked, which should be correct for the 15.8-equivalent tag. So I'd expect 10.3.x for this merge, but the banner text has remained the same.  I'd like to ensure we have the correct versions reported for this merge if possible. @ninjarobot @cartermp @dsyme.

**Comment by baronfel** [comment]
All of the errors on the single failing travis build (mono 5.8, linux) are related to loading the now-bundled optdata/sigdata, but it seems like the FSharp.Core included in mono 5.8 may not co-locate those files anymore:
```
FSC : error FS1225: File '/usr/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.optdata' not found alongside FSharp.Core. File expected in /usr/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.optdata. Consider upgrading to a more recent version of FSharp.Core, where this file is no longer be required. [/home/travis/build/fsharp/fsharp/tests/projects/Sample_MonoDevelop_3_2_8_Console/Sample_MonoDevelop_3_2_8_Console/Sample_MonoDevelop_3_2_8_Console.fsproj]
  
FSC : error FS0229: Error opening binary file '/usr/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.dll': The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: File '/usr/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.optdata' not found alongside FSharp.Core. File expected in /usr/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.optdata. Consider upgrading to a more recent version of FSharp.Core, where this file is no longer be required.) [/home/travis/build/fsharp/fsharp/tests/projects/Sample_MonoDevelop_3_2_8_Console/Sample_MonoDevelop_3_2_8_Console/Sample_MonoDevelop_3_2_8_Console.fsproj]
  
FSC : error FS3160: Problem reading assembly '/usr/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.dll': The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: Error opening binary file '/usr/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.dll': The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: File '/usr/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.optdata' not found alongside FSharp.Core. File expected in /usr/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.optdata. Consider upgrading to a more recent version of FSharp.Core, where this file is no longer be required.)) [/home/travis/build/fsharp/fsharp/tests/projects/Sample_MonoDevelop_3_2_8_Console/Sample_MonoDevelop_3_2_8_Console/Sample_MonoDevelop_3_2_8_Console.fsproj]
  
error FS0073 : internal error : BuildFrameworkTcImports: no successful import of /usr/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.dll [/home/travis/build/fsharp/fsharp/tests/projects/Sample_MonoDevelop_3_2_8_Console/Sample_MonoDevelop_3_2_8_Console/Sample_MonoDevelop_3_2_8_Console.fsproj]
```

The source error is thrown when the sigdata/optdata aren't found in the referenced FSharp.Core AND aren't colocated with it. So something is definitely interesting there. Odd that the OSX packaging doesn't seem to share that issue.

**Comment by dsyme** [comment]
That's a very odd error to be getting.... It's like an old F# compiler is being used here

**Comment by dsyme** [comment]
@baronfel I've restarted the CI on this to see status on Mono nightly.  I think we should ignore Mono 5.8.0.

**Comment by baronfel** [comment]
Agreed. What should the build targets be? 5.12 (May 2018) and up?  Even more recent?  I think there's a greater culture on the part of mono users for updating mono (especially because the 5.x versions have been so stable) so I don't necessarily think that sticking to a low 5.x mono is required.

**Comment by dsyme** [comment]
Mono 5.18 should be added

**Comment by baronfel** [comment]
right now `latest` is `5.18`, but we can add `5.18` as an explicit target to prevent drift.

**Comment by baronfel** [comment]
@dsyme unrelated, but what do I have to do to cancel a build run on travis? Is there a permission for that? in cases like these I'd like to abort all runs as soon as I see a problem arise, to save time.

**Comment by dsyme** [comment]
@baronfel I'll see if I can get you the permissions

**Comment by dsyme** [comment]
@baronfel I'm not sure how to give access.  I've added you as a maintainer to this repo, perhaps that's what's needed.  Or maybe you need to be admin on the "fsharp" org

**Comment by baronfel** [comment]
Certainly looking alright on the majority of the newer monos, though 5.18 is breaking consistently. Looks like the proto build can't find System.X references?
```
/home/travis/build/fsharp/fsharp/packages/FSharp.Compiler.Tools.4.1.27/tools/fsc.exe -o:obj/Proto/net40/FSharp.Core.dll
  -g
  --debug:portable
  --noframework
  --baseaddress:0x05000000
  --define:MSBUILD_AT_LEAST_14
  --define:BUILDING_WITH_LKG
  --define:FSHARP_CORE
  --define:DEBUG
  --define:NO_STRONG_NAMES
  --define:CROSS_PLATFORM_COMPILER
  --define:ENABLE_MONO_SUPPORT
  --define:BE_SECURITY_TRANSPARENT
  --define:FX_LCIDFROMCODEPAGE
  --doc:/home/travis/build/fsharp/fsharp/src/fsharp/FSharp.Core/../../../Proto/net40/bin/FSharp.Core.xml
  --keyfile:/home/travis/build/fsharp/fsharp/src/fsharp/FSharp.Core/../../fsharp/msft.pubkey
  --delaysign+
  --optimize+
  --resource:obj/Proto/net40/FSCore.resources
  --target:library
  --nowarn:69,65,54,61,75,45,55,62,75,1204
  --warn:3
  --warnaserror
  --warnaserror:76
  --fullpaths
  --flaterrors
  --subsystemversion:6.00
  --highentropyva+
  --times
  --warnon:1182
  --compiling-fslib
  --extraoptimizationloops:1
  --warnon:3218
  --maxerrors:20
  --warnon:1182
  --compiling-fslib
  --maxerrors:20
  --extraoptimizationloops:1
  --compiling-fslib-40
  --version:4.5.0.0
  prim-types-prelude.fsi
  prim-types-prelude.fs
  SR.fs
  prim-types.fsi
  prim-types.fs
  local.fsi
  local.fs
  array2.fsi
  array2.fs
  option.fsi
  option.fs
  result.fsi
  result.fs
  collections.fsi
  collections.fs
  seqcore.fsi
  seqcore.fs
  seq.fsi
  seq.fs
  string.fsi
  string.fs
  list.fsi
  list.fs
  array.fsi
  array.fs
  array3.fsi
  array3.fs
  map.fsi
  map.fs
  set.fsi
  set.fs
  ../../utils/reshapedreflection.fs
  reflect.fsi
  reflect.fs
  math/n.fsi
  math/n.fs
  math/z.fsi
  math/z.fs
  ../../utils/sformat.fsi
  ../../utils/sformat.fs
  printf.fsi
  printf.fs
  quotations.fsi
  quotations.fs
  nativeptr.fsi
  nativeptr.fs
  event.fsi
  event.fs
  async.fsi
  async.fs
  eventmodule.fsi
  eventmodule.fs
  observable.fsi
  observable.fs
  mailbox.fsi
  mailbox.fs
  Linq.fsi
  Linq.fs
  MutableTuple.fs
  QueryExtensions.fs
  Query.fsi
  Query.fs
  SI.fs
  fslib-extra-pervasives.fsi
  fslib-extra-pervasives.fs
  /tmp/.NETFramework,Version=v4.5.AssemblyAttributes.fs
```

I don't see any references to System.Collections.Generic in that command line, so that explains why the `HashSet` type can't be found.

**Comment by baronfel** [comment]
I'm able to reproduce the mono 5.18 build failures locally using mono 5.18 on osx. The failing message is:
>  FSC : error FS0193: The module/namespace 'Microsoft.FSharp.Core' from compilation unit 'FSharp.Core' did not contain the namespace, module or type 'byref`1' [/Users/chethusk/oss/fsharp/src/fsharp/FSharp.Core/FSharp.Core.fsproj]

but the type does exist in `prim-types.fs`.  The full command line is below. This is a bit of a guess, but does the version of FSharp.Core the proto-compiler uses contain byref? A quick check suggests it does, because it includes FSharp.Core as a project reference.  @dsyme any quick ideas/bright insights?

<details>
<summary>Full command line + output</summary>
```
 /Users/chethusk/oss/fsharp/src/fsharp/FSharp.Core/../../../Proto/net40/bin/fsc.exe -o:obj/Release/net40/FSharp.Core.dll
  -g
  --debug:portable
  --noframework
  --baseaddress:0x05000000
  --define:MSBUILD_AT_LEAST_14
  --define:FSHARP_CORE
  --define:TRACE
  --define:CROSS_PLATFORM_COMPILER
  --define:ENABLE_MONO_SUPPORT
  --define:BE_SECURITY_TRANSPARENT
  --define:FX_LCIDFROMCODEPAGE
  --doc:/Users/chethusk/oss/fsharp/src/fsharp/FSharp.Core/../../../Release/net40/bin/FSharp.Core.xml
  --keyfile:/Users/chethusk/oss/fsharp/src/fsharp/FSharp.Core/../../fsharp/msft.pubkey
  --delaysign+
  --optimize+
  --resource:obj/Release/net40/FSCore.resources
  -r:/Library/Frameworks/Mono.framework/Versions/Current/Commands/../lib/mono/4.5/mscorlib.dll
  -r:/Library/Frameworks/Mono.framework/Versions/Current/Commands/../lib/mono/4.5/System.Core.dll
  -r:/Library/Frameworks/Mono.framework/Versions/Current/Commands/../lib/mono/4.5/System.dll
  -r:/Library/Frameworks/Mono.framework/Versions/Current/Commands/../lib/mono/4.5/System.Numerics.dll
  --target:library
  --nowarn:69,65,54,61,75,45,55,62,75,1204
  --warn:3
  --warnaserror
  --warnaserror:76
  --fullpaths
  --flaterrors
  --subsystemversion:6.00
  --highentropyva+
  --times
  --warnon:1182
  --compiling-fslib
  --extraoptimizationloops:1
  --warnon:3218
  --maxerrors:20
  --warnon:1182
  --compiling-fslib
  --maxerrors:20
  --extraoptimizationloops:1
  --compiling-fslib-40
  prim-types-prelude.fsi
  prim-types-prelude.fs
  obj/Release/net40/FSCore.fs
  /var/folders/80/y0q8bqgx29bd8g3h0tlt00k00000gn/T/.NETFramework,Version=v4.5.AssemblyAttributes.fs
  prim-types.fsi
  prim-types.fs
  local.fsi
  local.fs
  array2.fsi
  array2.fs
  option.fsi
  option.fs
  result.fsi
  result.fs
  collections.fsi
  collections.fs
  seqcore.fsi
  seqcore.fs
  seq.fsi
  seq.fs
  string.fsi
  string.fs
  list.fsi
  list.fs
  array.fsi
  array.fs
  array3.fsi
  array3.fs
  map.fsi
  map.fs
  set.fsi
  set.fs
  ../../utils/reshapedreflection.fs
  reflect.fsi
  reflect.fs
  math/n.fsi
  math/n.fs
  math/z.fsi
  math/z.fs
  ../../utils/sformat.fsi
  ../../utils/sformat.fs
  printf.fsi
  printf.fs
  quotations.fsi
  quotations.fs
  nativeptr.fsi
  nativeptr.fs
  event.fsi
  event.fs
  async.fsi
  async.fs
  eventmodule.fsi
  eventmodule.fs
  observable.fsi
  observable.fs
  mailbox.fsi
  mailbox.fs
  Linq.fsi
  Linq.fs
  MutableTuple.fs
  QueryExtensions.fs
  Query.fsi
  Query.fs
  SI.fs
  fslib-extra-pervasives.fsi
  fslib-extra-pervasives.fs
  obj/Release/net40/FSharp.Core.AssemblyVersion.fs
  
  Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
  Copyright (c) Microsoft Corporation. All Rights Reserved.
  TIME:  0.6 Delta:  0.2 Mem:  83 G0:   0 G1:  0 G2:  0 [Import mscorlib and FSharp.Core.dll]
  TIME:  1.8 Delta:  1.2 Mem: 390 G0:   2 G1:  0 G2:  0 [Parse inputs]
  TIME:  1.8 Delta:  0.0 Mem: 390 G0:   0 G1:  0 G2:  0 [Import non-system references]
  
FSC : error FS0193: The module/namespace 'Microsoft.FSharp.Core' from compilation unit 'FSharp.Core' did not contain the namespace, module or type 'byref`1' [/Users/chethusk/oss/fsharp/src/fsharp/FSharp.Core/FSharp.Core.fsproj]
```
</details>

**Comment by dsyme** [comment]
@baronfel Yes looks like an out-of-date proto. Will work on it

**Comment by dsyme** [comment]
Hmm it's odd I was able to build clean on Mono 5.18.1 just now.

**Comment by dsyme** [comment]
I'm going to pull this now, I'm satisfied it's good after building clean against latest Mono in a docker container

**Comment by baronfel** [comment]
Ok, thanks for taking a look and finding that off Soon! I'll get to work on the 16.0 merge next
