### ISSUE TITLE
Console colors are messed up on Linux

### ISSUE THREAD

**Issue by ismail** [fsharp/fsharp#412]
Using latest master with mono 3.12.1:

[~]> fsc.exe --nologo
1%{8}%<%t31%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;1%;m
error FS0207: No inputs specified
1%{8}%<%t37%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;7%;m  

Apparently its not using the right color sequence.

**Comment by dsyme** [comment]
This looks likely to be a Mono bug - fsc.exe just uses standard console color calls.

**Comment by ismail** [comment]
Ah indeed, mono 4.0 works just fine. Thanks!

**Comment by ismail** [comment]
Also I should point out that latest stable release does not compile with Mono 4.0, only latest trunk does. It would be very nice to have a new stable release.

**Comment by dsyme** [comment]
You mean the latest tag?

**Comment by ismail** [comment]
Yes the master compiles fine.

**Comment by dsyme** [comment]
3.1.1.32 is tagged now

**Comment by ismail** [comment]
Yes, currently testing it. Will report here.

**Comment by ismail** [comment]
I manually compiled master with mono-4.0 fine but when I package it as an rpm it fails to build, even though no patch is applied and only ./configure --prefix=/usr. Here is the error:

[  220s] Errors:
[  220s] 
[  220s] /home/abuild/rpmbuild/BUILD/fsharp-3.1.1.32/src/fsharp/FSharp.Data.TypeProviders/FSharp.Data.TypeProviders.fsproj (default targets) ->
[  220s] /home/abuild/rpmbuild/BUILD/fsharp-3.1.1.32/lib/bootstrap/4.0/Microsoft.FSharp.Targets (CoreCompile target) ->
[  220s] 
[  220s]        /home/abuild/rpmbuild/BUILD/fsharp-3.1.1.32/src/fsharp/FSharp.Data.TypeProviders/TypeProvidersImpl.fs(723,108): error FS0039: The type 'ServiceModel' is not defined
[  220s]        /home/abuild/rpmbuild/BUILD/fsharp-3.1.1.32/src/fsharp/FSharp.Data.TypeProviders/TypeProvidersImpl.fs(723,29): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
[  220s]        /home/abuild/rpmbuild/BUILD/fsharp-3.1.1.32/src/fsharp/FSharp.Data.TypeProviders/TypeProvidersImpl.fs(724,27): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
[  220s] 
[  220s]         1 Warning(s)
[  220s]         3 Error(s)

I am guessing some dependency is missing.

**Comment by ismail** [comment]
3.1.1.32 builds fine thanks a lot! But the real problem with older release was a missing dependency on mono-wcf. But a new release can't hurt either ;)
