### PR TITLE
Changes to make the build work with Mono 4.9+

### LINKED ISSUE #685: Doesn't compile with Mono master (4.9+)
Please provide a succinct description of the issue.

Build error when compiling with Mono 4.9

#### Repro steps

Provide the steps required to reproduce the problem

1. Install Mono 4.9 https://bosstoragemirror.blob.core.windows.net/wrench/mono-master/c1/c1c09bc78d33dda29a4e53aa833f8ed09bbadaf2/MonoFramework-MDK-4.9.4.26.macos10.xamarin.universal.pkg

2. Build this repo
```
./autogen.sh --prefix=/Library/Frameworks/Mono.framework/Versions/4.9.4
make
```
#### Expected behavior

It should build

#### Actual behavior

```
XBuild Engine Version 14.0
Mono, Version 4.9.4.0
Copyright (C) 2005-2013 Various Mono authors

Build started 3/21/2017 1:12:44 PM.
__________________________________________________
Project "/Users/jason/src/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj" (default target(s)):
	Target CallFsSrGen:
		Created directory "obj//net40/"
		Executing: mono /Users/jason/src/fsharp/packages/FSharp.Compiler.Tools.4.0.1.21/tools/fsi.exe --exec "/Users/jason/src/fsharp/src/scripts/fssrgen.fsx" "/Users/jason/src/fsharp/src/fsharp/FSharp.Build/FSBuild.txt" "obj//net40/FSBuild.fs"  "obj//net40/FSBuild.resx"
		error FS0193: Specified method is not supported.
/Users/jason/src/fsharp/src/scripts/fssrgen.targets: error : Command 'mono /Users/jason/src/fsharp/packages/FSharp.Compiler.Tools.4.0.1.21/tools/fsi.exe --exec "/Users/jason/src/fsharp/src/scripts/fssrgen.fsx" "/Users/jason/src/fsharp/src/fsharp/FSharp.Build/FSBuild.txt" "obj//net40/FSBuild.fs"  "obj//net40/FSBuild.resx" ' exited with code: 1.
	Task "Exec" execution -- FAILED
	Done building target "CallFsSrGen" in project "/Users/jason/src/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj".-- FAILED
Done building project "/Users/jason/src/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj".-- FAILED

Build FAILED.
Errors:

/Users/jason/src/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj (default targets) ->
/Users/jason/src/fsharp/src/scripts/fssrgen.targets (CallFsSrGen target) ->

	/Users/jason/src/fsharp/src/scripts/fssrgen.targets: error : Command 'mono /Users/jason/src/fsharp/packages/FSharp.Compiler.Tools.4.0.1.21/tools/fsi.exe --exec "/Users/jason/src/fsharp/src/scripts/fssrgen.fsx" "/Users/jason/src/fsharp/src/fsharp/FSharp.Build/FSBuild.txt" "obj//net40/FSBuild.fs"  "obj//net40/FSBuild.resx" ' exited with code: 1.

	 0 Warning(s)
	 1 Error(s)

Time Elapsed 00:00:02.9666400
make[3]: *** [build-proto] Error 1
make[2]: *** [build-proto] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

#### Known workarounds

None

#### Related information 

Provide any related information 

* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Editing Tools (e.g. Visual Studio Version)
* Links to F# RFCs or entries on http://fslang.uservoice.com
* Links to performance testing scripts
* Indications of severity

### PR DESCRIPTION
**Pull request by nosami**
Looks like the problem is due to this commit to
Mono https://github.com/mono/mono/commit/efd53c8e2f1823568309a2920091b724be0feff8
Mono's internal System.Reflection.Emit.MonoGenericClass was renamed
to System.Reflection.Emit.TypeBuilderInstantiation

That broke the workaround in https://github.com/fsharp/fsharp/blob/5a942daf930d7023c78f578ec6876b86a6f13f1e/src/absil/ilreflect.fs#L619-L623 .

fixes #685

### CODE REVIEW

**Comment by nosami** [comment]
We would need a bump to the `FSharp.Compiler.Tools` nuget package containing this fix before we can build on Mono again.

I tested it by copying the output of this build into the `packages/FSharp.Compiler.Tools.4.0.1.21/tools` folder and then running `mono /Users/jason/src/fsharp/packages/FSharp.Compiler.Tools.4.0.1.21/tools/fsi.exe --exec "/Users/jason/src/fsharp/src/scripts/fssrgen.fsx" "/Users/jason/src/fsharp/src/fsharp/FSharp.Build/FSBuild.txt" "obj//net40/FSBuild.fs"  "obj//net40/FSBuild.resx"` from `fsharp/FSharp.Build`

```
✔ ~/src/fsharp [master ↑·1|⚑ 1]
12:32 $ cd src/fsharp/FSharp.Build
✔ ~/src/fsharp/src/fsharp/FSharp.Build [master ↑·1|⚑ 1]
12:32 $ mono /Users/jason/src/fsharp/packages/FSharp.Compiler.Tools.4.0.1.21/tools/fsi.exe --exec "/Users/jason/src/fsharp/src/scripts/fssrgen.fsx" "/Users/jason/src/fsharp/src/fsharp/FSharp.Build/FSBuild.txt" "obj//net40/FSBuild.fs"  "obj//net40/FSBuild.resx"
fssrgen: args = [|"/Users/jason/src/fsharp/src/scripts/fssrgen.fsx";
  "/Users/jason/src/fsharp/src/fsharp/FSharp.Build/FSBuild.txt";
  "obj//net40/FSBuild.fs"; "obj//net40/FSBuild.resx"|]
fssrgen.fsx: Reading /Users/jason/src/fsharp/src/fsharp/FSharp.Build/FSBuild.txt
fssrgen.fsx: Parsing /Users/jason/src/fsharp/src/fsharp/FSharp.Build/FSBuild.txt
fssrgen.fsx: Validating /Users/jason/src/fsharp/src/fsharp/FSharp.Build/FSBuild.txt
fssrgen.fsx: Validating uniqueness of /Users/jason/src/fsharp/src/fsharp/FSharp.Build/FSBuild.txt
fssrgen.fsx: Generating /Users/jason/src/fsharp/src/fsharp/FSharp.Build/obj//net40/FSBuild.fs
fssrgen.fsx: Generating resource methods for /Users/jason/src/fsharp/src/fsharp/FSharp.Build/obj//net40/FSBuild.fs
fssrgen.fsx: Generating .resx for /Users/jason/src/fsharp/src/fsharp/FSharp.Build/obj//net40/FSBuild.fs
fssrgen.fsx: Done /Users/jason/src/fsharp/src/fsharp/FSharp.Build/obj//net40/FSBuild.fs
```

**Comment by nosami** [comment]
Build passed against Mono 4.8.0 and 4.4.2. AppVeyor failed with an unrleated error

```
Time Elapsed 00:00:20.03
"Finished"
build-netcore.bat
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.
Build started 3/27/2017 11:36:59 AM.
     1>Project "C:\projects\fsharp\lib\netcore\build-fsc-netcore.proj" on node 1 (default targets).
     1>RestoreFscNetcore:
         dotnet restore
     1>MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file. [C:\projects\fsharp\lib\netcore\build-fsc-netcore.proj]
     1>C:\projects\fsharp\lib\netcore\build-fsc-netcore.proj(67,5): error MSB3073: The command "dotnet restore" exited with code 1.
     1>Done Building Project "C:\projects\fsharp\lib\netcore\build-fsc-netcore.proj" (default targets) -- FAILED.
Build FAILED.
       "C:\projects\fsharp\lib\netcore\build-fsc-netcore.proj" (default target) (1) ->
```

**Comment by dsyme** [comment]
@nosami Thanks, that's great.  Could you cherry pick and submit to http://Microsoft/visualfsharp as well please? (normally we'd integrate it across but this needs to be done more rapidly)

**Comment by nosami** [comment]
sure!
